import type { Metadata } from 'next';
import localFont from 'next/font/local';

import { ThemeProvider } from '@/components/ThemeProvider';

// TODO: Optimize fonts.
const interFont = localFont({
  src: [
    {
      path: './fonts/InterVariable.ttf',
      style: 'normal',
    },
    {
      path: './fonts/InterVariable-Italic.ttf',
      style: 'italic',
    },
  ],
  display: 'swap',
  variable: '--font-inter',
});

import './globals.css';

import LayoutHeader from '@/components/LayoutHeader';

import { cn } from '@/utils/cn';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={cn(
          'bg-background font-sans antialiased',
          interFont.variable,
        )}
      >
        <LayoutHeader />

        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          disableTransitionOnChange
        >
          <main className='p-4'>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
